baseurl = "http://depositfix.com"
title = "DepositFix - Payment Solution for HubSpot"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Integration Agent 2016"

disqusShortname = "integrationagent"

[author]
  name = "Denis Lunev"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "DepositFix"
  Author = "Denis Lunev"
  email = "denis@integrationagent.com"
  Ganalytics = "UA-7712728-16"

[[menu.main]]
  name = "Fee Calculator"
  url = "/calc"
  weight = -200
