baseurl = "https://integrationagent"
title = "Integration Agent - Get the most out of your marketing automation"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Integration Agent 2016"

disqusShortname = "integrationagent"

[author]
  name = "Denis Lunev"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Integration Agent"
  Author = "Denis Lunev"
  email = "denis@integrationagent.com"
  Ganalytics = "UA-7712728-16"

[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = -200

[[menu.main]]
  name = "Products"
  url = "/products"
  weight = -180
