baseurl = "https://integrationagent.com"
title = "Integration Agent - Get the most out of your marketing automation"
canonifyurls = true
paginate = 10
languageCode = "en-us"
copyright = "Integration Agent 2016"
theme = "int-agent"
disqusShortname = "integrationagent"

[author]
  name = "Denis Lunev"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Integration Agent"
  Author = "Denis Lunev"
  email = "denis@integrationagent.com"
  Ganalytics = "UA-7712728-14"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "Services"
  url = "/services"
  weight = 2

[[menu.main]]
  name = "Products"
  url = "/products"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 4


